apiVersion: v1
kind: Pod
metadata:
  name: flask
  labels:
    env: test
    app: flask
    tier: hello
    owner: Dmytro
spec:
  containers:
  - name : container-python-flask
    image: dangerraider/flask_first:latest
    ports:
      - containerPort: 80
